#!/usr/bin/env zsh
# If not interactive, don't do anything
[[ $- != *i* ]] && return

#unset rc

## Launch wm
#if [ -z $DISPLAY ] && [ "$(tty)" = "/dev/tty1" ]; then
#  exec sway
#fi
## Launch tmux
# Source: https://unix.stackexchange.com/a/113768
if command -v tmux &> /dev/null && [[ ! "$TERM" =~ screen ]] && [ -z "$TMUX" ]; then
  exec tmux new-session -A -s 0
fi

# Source global definitions
if [ -f /etc/zsh/zprofile ]; then
	source /etc/zsh/zprofile
fi

# User specific environment
if ! [[ "$PATH" == *"$HOME/.local/bin:$HOME/bin:"* ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# User specific aliases and functions
# TODO: Make cross-shell aliases/functions dir
if [ -d ~/.config/shell/ ]; then
	for rc in ~/.config/shell/*; do
		if [ -f "$rc" ]; then
			source "$rc"
		fi
	done
fi


### Added by Zinit's installer
if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
    print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
    command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
    command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git" && \
        print -P "%F{33} %F{34}Installation successful.%f%b" || \
        print -P "%F{160} The clone has failed.%f%b"
fi

source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zdharma-continuum/zinit-annex-as-monitor \
    zdharma-continuum/zinit-annex-bin-gem-node \
    zdharma-continuum/zinit-annex-patch-dl \
    zdharma-continuum/zinit-annex-rust

zinit wait lucid for \
 atinit"ZINIT[COMPINIT_OPTS]=-C; zicompinit; zicdreplay" \
    zdharma-continuum/fast-syntax-highlighting \
 blockf \
    zsh-users/zsh-completions \
 atload"!_zsh_autosuggest_start" \
    zsh-users/zsh-autosuggestions
### End of Zinit's installer chunk

## Set base16 theme here (slow!)
if [ ! -f $HOME/.config/base16-project/base16_shell_theme ]; then
zinit ice atload"base16_catppuccin" # Theme if unset using 'base16_<theme>' command
fi
zinit light base16-project/base16-shell

# starship
if [ -x "$(command -v starship)" ]; then
  eval "$(starship init zsh)"
fi
