#!/bin/bash

# Default apps
# Editor
if command -v 'nvim'; then
  export EDITOR='nvim'
elif command -v 'vim'; then
  export EDITOR='vim'
elif command -v 'vi'; then
  export EDITOR='vi'
else
  export EDITOR='nano'
fi

# Enable native Wayland for FF if available
if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
  export MOZ_ENABLE_WAYLAND=1
fi
