#!/bin/bash

# PATH
if ! [[ "$PATH" == *"$HOME/.local/bin:$HOME/bin:"* ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Default apps
# Editor
if command -v 'nvim' > /dev/null; then
  export EDITOR='nvim'
elif command -v 'vim' > /dev/null; then
  export EDITOR='vim'
elif command -v 'vi' > /dev/null; then
  export EDITOR='vi'
else
  export EDITOR='nano'
fi

# Enable native Wayland for FF if available
if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
  export MOZ_ENABLE_WAYLAND=1
fi
