#!/bin/bash

# If not interactive, don't do anything
[[ $- != *i* ]] && return

# Source global definitions
if [ -f /etc/bashrc ]; then
	source /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" == *"$HOME/.local/bin:$HOME/bin:"* ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# User specific aliases and functions
# TODO: Make cross-shell aliases/functions dir
#if [ -d ~/.bashrc.d ]; then
#	for rc in ~/.bashrc.d/*; do
#		if [ -f "$rc" ]; then
#			source "$rc"
#		fi
#	done
#fi

#unset rc

# starship
if [ -x "$(command -v starship)" ]; then
  eval "$(starship init bash)"
fi

# tmux
# WARNING: commented out as it introduces issue with neovim terminals.
# a more robust implementation can be expected when zsh plugins are used,
# but i'll try to do it in bash :)
#if [[ "$TERM" != "tmux-256color" ]] && [[ "$TERM" != "tmux-256" ]] ; then
#  if tmux has-session; then
#    exec tmux attach 
#  else
#    exec tmux
#  fi
#fi
