theme = "dracula"
icons = "material-nf"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
format_mem = "$mem_used_percents"
format_swap = "$swap_used_percents"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1

[[block]]
block = "net"

[[block]]
block = "sound"

[[block]]
block = "backlight"

[[block]]
block = "time"
interval = 5
format = "$icon $timestamp.datetime(f:'%a %d/%m %R')"

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT0"
